name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  diff-openapi-spec:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install -e '.[dev]'
          npm ci

      - name: Generate OpenAPI spec from the application
        run: |
          cp specs/indico-hub.yaml specs/indico-hub.old.yaml
          npm run api-spec

      - name: Check OpenAPI spec for changes
        run: diff --color -u specs/indico-hub.old.yaml specs/indico-hub.yaml

  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run isort
        run: isort --diff --check-only setup.py indico_hub/

      - name: Run flake8
        run: flake8 setup.py indico_hub/

      - name: Run black
        run: black --check --diff --color setup.py indico_hub/
